name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

# Add permissions at workflow level
permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov bandit safety
        pip install -e .
    
    - name: Run linting
      run: |
        pip install flake8
        flake8 . --max-line-length=79 --exclude=.git,__pycache__,build,dist
    
    - name: Run security checks
      run: |
        bandit -r . -f json -o bandit-results.json
        safety check
    
    - name: Verify AWS Credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
          echo "AWS credentials not found in GitHub Secrets"
          exit 1
        fi
        # Verify credentials are valid
        aws sts get-caller-identity || exit 1
    
    - name: Run AWS Security Scan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
      run: |
        # Run all scanner modules
        python -c "
        from scanner import s3, iam, ec2, sg
        from alert.email import send_email_alert
        from alert.slack import send_slack_alert
        import json
        import os
        
        findings = []
        findings.extend(s3.scan())
        findings.extend(iam.scan())
        findings.extend(ec2.scan())
        findings.extend(sg.scan())
        
        # Sanitize findings to remove sensitive data
        sanitized_findings = []
        for finding in findings:
            sanitized = finding.copy()
            # Only redact sensitive parts of resource names
            if 'resource' in sanitized:
                resource = sanitized['resource']
                # Keep resource IDs but redact sensitive parts
                if isinstance(resource, str):
                    if 'arn:aws:' in resource:
                        # For ARNs, keep service and resource type but redact account and name
                        parts = resource.split(':')
                        if len(parts) >= 6:
                            sanitized['resource'] = f"{parts[2]}:{parts[5]}"
                    elif 'i-' in resource:
                        # For EC2 instances, keep instance ID
                        sanitized['resource'] = resource
                    elif 'sg-' in resource:
                        # For security groups, keep group ID
                        sanitized['resource'] = resource
                    elif 'vol-' in resource:
                        # For volumes, keep volume ID
                        sanitized['resource'] = resource
                    else:
                        # For other resources, redact if it might contain sensitive info
                        sanitized['resource'] = 'REDACTED'
            
            # Redact sensitive details but keep non-sensitive information
            if 'details' in sanitized:
                details = sanitized['details']
                if isinstance(details, str):
                    if any(sensitive in details.lower() for sensitive in ['password', 'key', 'secret', 'token']):
                        sanitized['details'] = 'REDACTED'
            
            sanitized_findings.append(sanitized)
        
        # Save sanitized findings to file
        with open('aws-scan-results.json', 'w') as f:
            json.dump(sanitized_findings, f, indent=2)
            
        # Send notifications for high and medium risk findings
        high_risk_findings = [f for f in findings if f['risk'] == 'HIGH']
        medium_risk_findings = [f for f in findings if f['risk'] == 'MEDIUM']
        
        # Prepare email config
        email_config = {
            'smtp_server': os.getenv('SMTP_SERVER'),
            'smtp_port': int(os.getenv('SMTP_PORT', 587)),
            'username': os.getenv('SMTP_USERNAME'),
            'password': os.getenv('SMTP_PASSWORD'),
            'sender': os.getenv('SMTP_USERNAME'),
            'recipient': os.getenv('EMAIL_RECIPIENT')
        }
        
        # Send email alerts
        if high_risk_findings or medium_risk_findings:
            send_email_alert(high_risk_findings + medium_risk_findings, email_config)
            
        # Send Slack alerts for high risk findings
        slack_webhook = os.getenv('SLACK_WEBHOOK_URL')
        if slack_webhook:
            for finding in high_risk_findings:
                send_slack_alert(finding, slack_webhook)
        "
        
        # Check if any high risk findings
        if jq -e '.[] | select(.risk == "HIGH")' aws-scan-results.json > /dev/null; then
          echo "High risk findings detected!"
          cat aws-scan-results.json
          exit 1
        fi
    
    - name: Run tests with coverage
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
          echo "AWS credentials not found in GitHub Secrets"
          exit 1
        fi
        pytest --cov=. --cov-report=xml --cov-report=term-missing
    
    - name: Build and test Docker image
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
          echo "AWS credentials not found in GitHub Secrets"
          exit 1
        fi
        docker build -t aws-auditor .
        docker run --rm aws-auditor pytest
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          coverage.xml
          bandit-results.json
          aws-scan-results.json
        retention-days: 7
        if-no-files-found: warn

    - name: Create Security Report
      if: always()
      run: |
        echo "## Security Scan Summary" > security-report.md
        echo "**WARNING: This is a public repository. Sensitive data has been redacted.**" >> security-report.md
        echo "" >> security-report.md
        echo "### High Risk Findings" >> security-report.md
        jq -r '.[] | select(.risk == "HIGH") | "- " + .type + ": " + .resource + "\n  Issue: " + .issue + "\n  CIS Rule: " + .cis_rule + "\n  Remediation: " + .remediation' aws-scan-results.json >> security-report.md || echo "No high risk findings" >> security-report.md
        echo "" >> security-report.md
        echo "### Medium Risk Findings" >> security-report.md
        jq -r '.[] | select(.risk == "MEDIUM") | "- " + .type + ": " + .resource + "\n  Issue: " + .issue + "\n  CIS Rule: " + .cis_rule + "\n  Remediation: " + .remediation' aws-scan-results.json >> security-report.md || echo "No medium risk findings" >> security-report.md

    - name: Upload Security Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: security-report
        path: security-report.md
        retention-days: 7
        if-no-files-found: warn

    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'CI/CD Pipeline Failed',
            body: 'The CI/CD pipeline has failed. Please check the workflow run for details.'
          })
